// Seed exam questions for each role level
// Real medical questions relevant to MBBS students in India

export type QuestionType = "mcq" | "descriptive";

export interface ExamQuestion {
  id: string;
  type: QuestionType;
  text: string;
  options?: string[];
  correctIndex?: number;
  subject: string;
  roleLevel: "mbbs" | "junior" | "senior" | "professor" | "hod";
  marks: number;
}

export const EXAM_SEED_QUESTIONS: ExamQuestion[] = [
  // ─── MBBS Level MCQ (20 questions) ─────────────────────────────────
  {
    id: "mbbs_mcq_1",
    type: "mcq",
    text: "Malaria ka causative organism kaunsa hai?",
    options: [
      "Plasmodium vivax",
      "Entamoeba histolytica",
      "Leishmania donovani",
      "Trypanosoma cruzi",
    ],
    correctIndex: 0,
    subject: "Microbiology",
    roleLevel: "mbbs",
    marks: 1,
  },
  {
    id: "mbbs_mcq_2",
    type: "mcq",
    text: "Dengue fever mein konsa test sabse pehle positive hota hai (fever ke 1st-3rd day)?",
    options: ["IgM antibody", "IgG antibody", "NS1 antigen", "Widal test"],
    correctIndex: 2,
    subject: "Medicine",
    roleLevel: "mbbs",
    marks: 1,
  },
  {
    id: "mbbs_mcq_3",
    type: "mcq",
    text: "Tuberculosis ka primary treatment regimen (RNTCP) kaunsa hai?",
    options: ["2HRZE/4HR", "2HRZ/4H3R3", "6HRE/2S", "4HRZE/2HR"],
    correctIndex: 0,
    subject: "Medicine",
    roleLevel: "mbbs",
    marks: 1,
  },
  {
    id: "mbbs_mcq_4",
    type: "mcq",
    text: "Typhoid fever mein Widal test positive hota hai agglutination titer kab se?",
    options: ["1:20", "1:40", "1:80", "1:160"],
    correctIndex: 3,
    subject: "Microbiology",
    roleLevel: "mbbs",
    marks: 1,
  },
  {
    id: "mbbs_mcq_5",
    type: "mcq",
    text: "Cholera ka causative organism kaunsa hai?",
    options: [
      "Vibrio cholerae El Tor",
      "Salmonella typhi",
      "Shigella dysenteriae",
      "E. coli O157:H7",
    ],
    correctIndex: 0,
    subject: "Microbiology",
    roleLevel: "mbbs",
    marks: 1,
  },
  {
    id: "mbbs_mcq_6",
    type: "mcq",
    text: "Type 1 Diabetes Mellitus mein kaunsa HLA antigen associated hai?",
    options: ["HLA-DR3, DR4", "HLA-B27", "HLA-DR2", "HLA-A3"],
    correctIndex: 0,
    subject: "Medicine",
    roleLevel: "mbbs",
    marks: 1,
  },
  {
    id: "mbbs_mcq_7",
    type: "mcq",
    text: "Hypertension ka first-line treatment drug class (without comorbidities) kaunsa hai?",
    options: [
      "Beta blockers",
      "ACE inhibitors",
      "Thiazide diuretics",
      "Calcium channel blockers",
    ],
    correctIndex: 2,
    subject: "Pharmacology",
    roleLevel: "mbbs",
    marks: 1,
  },
  {
    id: "mbbs_mcq_8",
    type: "mcq",
    text: "Rabies vaccine ka standard post-exposure prophylaxis schedule kaunsa hai?",
    options: [
      "Days 0, 7, 21",
      "Days 0, 3, 7, 14, 28 (Essen schedule)",
      "Days 0, 14, 28",
      "Days 0, 7, 14",
    ],
    correctIndex: 1,
    subject: "Community Medicine",
    roleLevel: "mbbs",
    marks: 1,
  },
  {
    id: "mbbs_mcq_9",
    type: "mcq",
    text: "Leptospirosis mein kaunsa organ sabse zyada affected hota hai?",
    options: [
      "Liver and Kidneys (Weil's disease)",
      "Brain",
      "Lungs only",
      "Heart only",
    ],
    correctIndex: 0,
    subject: "Medicine",
    roleLevel: "mbbs",
    marks: 1,
  },
  {
    id: "mbbs_mcq_10",
    type: "mcq",
    text: "Chloroquine-resistant Malaria ke liye recommended treatment kaunsa hai?",
    options: [
      "Quinine alone",
      "Artemisinin Combination Therapy (ACT)",
      "Primaquine alone",
      "Doxycycline alone",
    ],
    correctIndex: 1,
    subject: "Pharmacology",
    roleLevel: "mbbs",
    marks: 1,
  },
  {
    id: "mbbs_mcq_11",
    type: "mcq",
    text: "Brucellosis ka treatment kaunsa hai?",
    options: [
      "Doxycycline + Rifampicin for 6 weeks",
      "Amoxicillin for 7 days",
      "Metronidazole for 2 weeks",
      "Ciprofloxacin alone for 3 days",
    ],
    correctIndex: 0,
    subject: "Medicine",
    roleLevel: "mbbs",
    marks: 1,
  },
  {
    id: "mbbs_mcq_12",
    type: "mcq",
    text: "Kyasanur Forest Disease (KFD) ka vector kaunsa hai?",
    options: [
      "Ixodes tick",
      "Haemaphysalis spinigera tick",
      "Anopheles mosquito",
      "Aedes mosquito",
    ],
    correctIndex: 1,
    subject: "Microbiology",
    roleLevel: "mbbs",
    marks: 1,
  },
  {
    id: "mbbs_mcq_13",
    type: "mcq",
    text: "Anemia of chronic disease mein serum iron aur TIBC kaise hote hain?",
    options: [
      "Iron low, TIBC high",
      "Iron low, TIBC low or normal",
      "Iron high, TIBC high",
      "Iron normal, TIBC low",
    ],
    correctIndex: 1,
    subject: "Medicine",
    roleLevel: "mbbs",
    marks: 1,
  },
  {
    id: "mbbs_mcq_14",
    type: "mcq",
    text: "Community-acquired pneumonia (CAP) ka most common causative organism kaunsa hai?",
    options: [
      "Klebsiella pneumoniae",
      "Streptococcus pneumoniae",
      "Pseudomonas aeruginosa",
      "Staphylococcus aureus",
    ],
    correctIndex: 1,
    subject: "Medicine",
    roleLevel: "mbbs",
    marks: 1,
  },
  {
    id: "mbbs_mcq_15",
    type: "mcq",
    text: "Hepatitis B ka vertical transmission (mother to child) rokne ke liye kya diya jata hai?",
    options: [
      "HB vaccine alone",
      "HBIG alone",
      "HB vaccine + HBIG within 12 hours of birth",
      "Interferon therapy",
    ],
    correctIndex: 2,
    subject: "Paediatrics",
    roleLevel: "mbbs",
    marks: 1,
  },
  {
    id: "mbbs_mcq_16",
    type: "mcq",
    text: "Acute MI (STEMI) mein ECG pe kya changes dikhte hain?",
    options: [
      "ST depression + T wave inversion",
      "ST elevation in affected leads + Q waves",
      "Widened QRS complex only",
      "PR interval prolongation",
    ],
    correctIndex: 1,
    subject: "Medicine",
    roleLevel: "mbbs",
    marks: 1,
  },
  {
    id: "mbbs_mcq_17",
    type: "mcq",
    text: "Appendicitis ka classic pain pattern kaunsa hai?",
    options: [
      "Starts periumbilical, shifts to RIF (McBurney's point)",
      "Starts in RIF, shifts to epigastric",
      "Constant severe epigastric pain",
      "Left iliac fossa pain with radiation to back",
    ],
    correctIndex: 0,
    subject: "Surgery",
    roleLevel: "mbbs",
    marks: 1,
  },
  {
    id: "mbbs_mcq_18",
    type: "mcq",
    text: "Diabetic Ketoacidosis (DKA) mein kaunsa electrolyte imbalance common hai?",
    options: [
      "Hypernatremia",
      "Total body potassium depletion (despite normal/high initial serum K+)",
      "Hyperkalemia throughout treatment",
      "Hypercalcemia",
    ],
    correctIndex: 1,
    subject: "Medicine",
    roleLevel: "mbbs",
    marks: 1,
  },
  {
    id: "mbbs_mcq_19",
    type: "mcq",
    text: "Tetanus prophylaxis ke liye TT injection injured adult ko kab dena chahiye?",
    options: [
      "Always regardless of vaccination history",
      "Only if last dose > 10 years ago (clean wound) or > 5 years (dirty wound)",
      "Never in adults",
      "Only if wound is > 24 hours old",
    ],
    correctIndex: 1,
    subject: "Surgery",
    roleLevel: "mbbs",
    marks: 1,
  },
  {
    id: "mbbs_mcq_20",
    type: "mcq",
    text: "DOTS strategy in tuberculosis — kya matlab hai?",
    options: [
      "Daily Oral Treatment Strategy",
      "Directly Observed Treatment, Short course",
      "Drug-resistant Oral Therapy Scheme",
      "Disease Observation and Testing System",
    ],
    correctIndex: 1,
    subject: "Community Medicine",
    roleLevel: "mbbs",
    marks: 1,
  },

  // ─── Junior Level MCQ (15 questions) ──────────────────────────────
  {
    id: "jr_mcq_1",
    type: "mcq",
    text: "Septic shock mein vasopressor of choice kaunsa hai?",
    options: ["Dopamine", "Epinephrine", "Norepinephrine", "Vasopressin"],
    correctIndex: 2,
    subject: "Medicine",
    roleLevel: "junior",
    marks: 2,
  },
  {
    id: "jr_mcq_2",
    type: "mcq",
    text: "Acute liver failure mein encephalopathy ke liye konsa treatment use hota hai?",
    options: [
      "Neomycin IV",
      "Lactulose orally + Rifaximin",
      "Metronidazole IV",
      "Vancomycin orally",
    ],
    correctIndex: 1,
    subject: "Medicine",
    roleLevel: "junior",
    marks: 2,
  },
  {
    id: "jr_mcq_3",
    type: "mcq",
    text: "COPD exacerbation mein optimal oxygen saturation target kya hai?",
    options: ["98-100%", "94-98%", "88-92%", "> 92%"],
    correctIndex: 2,
    subject: "Medicine",
    roleLevel: "junior",
    marks: 2,
  },
  {
    id: "jr_mcq_4",
    type: "mcq",
    text: "Fluid of choice in hypovolemic shock ke initial resuscitation mein kaunsa hai?",
    options: [
      "5% Dextrose",
      "Normal Saline (0.9% NaCl) or Ringer's Lactate",
      "Hypertonic saline 3%",
      "Albumin 20%",
    ],
    correctIndex: 1,
    subject: "Surgery",
    roleLevel: "junior",
    marks: 2,
  },
  {
    id: "jr_mcq_5",
    type: "mcq",
    text: "Drug of choice for Pneumocystis jiroveci pneumonia (PCP) treatment kaunsa hai?",
    options: [
      "Fluconazole",
      "Amphotericin B",
      "Co-trimoxazole (TMP-SMX)",
      "Dapsone",
    ],
    correctIndex: 2,
    subject: "Infectious Disease",
    roleLevel: "junior",
    marks: 2,
  },
  {
    id: "jr_mcq_6",
    type: "mcq",
    text: "Acute pancreatitis mein prognostic scoring system kaunsa use hota hai?",
    options: [
      "APACHE II / Ranson's criteria / Glasgow score",
      "CURB-65",
      "Wells score",
      "Child-Pugh score",
    ],
    correctIndex: 0,
    subject: "Surgery",
    roleLevel: "junior",
    marks: 2,
  },
  {
    id: "jr_mcq_7",
    type: "mcq",
    text: "Meningitis mein LP se CSF analysis — bacterial vs viral differential kya hota hai?",
    options: [
      "Bacterial: high protein, low glucose, polymorphs; Viral: mild protein rise, normal glucose, lymphocytes",
      "Bacterial: low protein, high glucose; Viral: high protein, low glucose",
      "Both have similar CSF profiles",
      "Bacterial: lymphocytes predominant; Viral: neutrophils predominant",
    ],
    correctIndex: 0,
    subject: "Medicine",
    roleLevel: "junior",
    marks: 2,
  },
  {
    id: "jr_mcq_8",
    type: "mcq",
    text: "Cardiac arrest mein adult CPR ratio (chest compressions: ventilations) kya hai?",
    options: ["15:2", "30:2", "5:1", "10:2"],
    correctIndex: 1,
    subject: "Medicine",
    roleLevel: "junior",
    marks: 2,
  },
  {
    id: "jr_mcq_9",
    type: "mcq",
    text: "Pulmonary embolism mein investigation of choice kya hai?",
    options: [
      "Chest X-ray",
      "V/Q scan",
      "CT Pulmonary Angiography (CTPA)",
      "Echo alone",
    ],
    correctIndex: 2,
    subject: "Medicine",
    roleLevel: "junior",
    marks: 2,
  },
  {
    id: "jr_mcq_10",
    type: "mcq",
    text: "Anaphylaxis ka first-line treatment kya hai?",
    options: [
      "IV hydrocortisone 200mg",
      "Chlorphenamine IV",
      "Epinephrine (Adrenaline) IM 0.5mg (1:1000)",
      "Salbutamol nebulization",
    ],
    correctIndex: 2,
    subject: "Medicine",
    roleLevel: "junior",
    marks: 2,
  },
  {
    id: "jr_mcq_11",
    type: "mcq",
    text: "Hyponatremia correction mein saline infusion ki rate kya honi chahiye?",
    options: [
      "Correct as fast as possible",
      "No more than 8-12 mEq/L per 24 hours to prevent osmotic demyelination",
      "Fixed 20 mEq/L per day",
      "Always use 3% saline",
    ],
    correctIndex: 1,
    subject: "Medicine",
    roleLevel: "junior",
    marks: 2,
  },
  {
    id: "jr_mcq_12",
    type: "mcq",
    text: "Chronic kidney disease staging mein Stage 3a ki GFR range kya hai?",
    options: ["< 15 mL/min", "15-29 mL/min", "45-59 mL/min", "30-44 mL/min"],
    correctIndex: 2,
    subject: "Medicine",
    roleLevel: "junior",
    marks: 2,
  },
  {
    id: "jr_mcq_13",
    type: "mcq",
    text: "Upper GI bleed mein endoscopy kab tak karni chahiye?",
    options: [
      "Within 24 hours of presentation (urgent)",
      "Only after 72 hours of stabilization",
      "Elective basis pe",
      "Only if bleeding doesn't stop in 48 hours",
    ],
    correctIndex: 0,
    subject: "Medicine",
    roleLevel: "junior",
    marks: 2,
  },
  {
    id: "jr_mcq_14",
    type: "mcq",
    text: "Acute stroke mein IV tPA (alteplase) dene ki time window kya hai?",
    options: [
      "Within 1 hour",
      "Within 3-4.5 hours of symptom onset",
      "Within 12 hours",
      "Within 24 hours",
    ],
    correctIndex: 1,
    subject: "Neurology",
    roleLevel: "junior",
    marks: 2,
  },
  {
    id: "jr_mcq_15",
    type: "mcq",
    text: "Status epilepticus (>5 mins) mein first-line treatment kya hai?",
    options: [
      "Phenytoin IV",
      "Lorazepam/Diazepam IV (benzodiazepine)",
      "Valproate IV",
      "Levetiracetam IV",
    ],
    correctIndex: 1,
    subject: "Neurology",
    roleLevel: "junior",
    marks: 2,
  },

  // ─── Junior Level Descriptive (3 questions) ───────────────────────
  {
    id: "jr_desc_1",
    type: "descriptive",
    text: "Dengue Hemorrhagic Fever (DHF) ka pathophysiology explain karein. DHF aur simple Dengue fever mein kya difference hai? WHO classification describe karein aur management outline karein.",
    subject: "Medicine",
    roleLevel: "junior",
    marks: 10,
  },
  {
    id: "jr_desc_2",
    type: "descriptive",
    text: "Sepsis-3 definition kya hai? SOFA score kaise calculate hota hai? Sepsis bundle (Hour-1 bundle) ke steps describe karein. Antibiotics choice aur source control ke baare mein explain karein.",
    subject: "Medicine",
    roleLevel: "junior",
    marks: 10,
  },
  {
    id: "jr_desc_3",
    type: "descriptive",
    text: "Acute MI (STEMI) mein emergency management describe karein. DAPT therapy, anticoagulation, aur reperfusion strategy (PCI vs thrombolysis) ke baare mein explain karein. Post-MI secondary prevention kya hai?",
    subject: "Cardiology",
    roleLevel: "junior",
    marks: 10,
  },

  // ─── Senior Level MCQ (10 questions) ─────────────────────────────
  {
    id: "sr_mcq_1",
    type: "mcq",
    text: "HbA1c level kya diagnosis karta hai Type 2 DM ka (ADA criteria)?",
    options: ["≥ 5.7%", "≥ 6.5%", "≥ 7.0%", "≥ 8.0%"],
    correctIndex: 1,
    subject: "Endocrinology",
    roleLevel: "senior",
    marks: 3,
  },
  {
    id: "sr_mcq_2",
    type: "mcq",
    text: "Child-Pugh Class C liver cirrhosis mein surgery ka operative mortality estimate kya hai?",
    options: ["< 5%", "10-15%", "25-30%", "> 80%"],
    correctIndex: 3,
    subject: "Surgery",
    roleLevel: "senior",
    marks: 3,
  },
  {
    id: "sr_mcq_3",
    type: "mcq",
    text: "Lupus nephritis Class IV (diffuse proliferative) ka treatment kya hai?",
    options: [
      "Hydroxychloroquine alone",
      "High-dose steroids + Mycophenolate or Cyclophosphamide",
      "NSAIDs only",
      "Azathioprine monotherapy",
    ],
    correctIndex: 1,
    subject: "Medicine",
    roleLevel: "senior",
    marks: 3,
  },
  {
    id: "sr_mcq_4",
    type: "mcq",
    text: "Multidrug-resistant TB (MDR-TB) mein minimum treatment duration kya hai?",
    options: [
      "6 months",
      "9 months",
      "18-24 months (shorter regimen 9-12 months where eligible)",
      "3 months",
    ],
    correctIndex: 2,
    subject: "Medicine",
    roleLevel: "senior",
    marks: 3,
  },
  {
    id: "sr_mcq_5",
    type: "mcq",
    text: "Severe pre-eclampsia mein antihypertensive drug of choice for acute management kaunsa hai?",
    options: [
      "Oral Amlodipine",
      "IV Labetalol or IV Hydralazine or oral Nifedipine",
      "IV Enalapril",
      "IV Metoprolol",
    ],
    correctIndex: 1,
    subject: "Gynaecology",
    roleLevel: "senior",
    marks: 3,
  },
  {
    id: "sr_mcq_6",
    type: "mcq",
    text: "Hemolytic Uremic Syndrome (HUS) mein classic triad kya hai?",
    options: [
      "Fever, jaundice, RUQ pain",
      "Microangiopathic hemolytic anemia, thrombocytopenia, acute kidney injury",
      "Anemia, splenomegaly, bleeding",
      "Hemolysis, elevated liver enzymes, low platelets",
    ],
    correctIndex: 1,
    subject: "Nephrology",
    roleLevel: "senior",
    marks: 3,
  },
  {
    id: "sr_mcq_7",
    type: "mcq",
    text: "Liver abscess mein choice of drainage kab nahi karna chahiye?",
    options: [
      "Abscess > 5 cm",
      "Left lobe abscess (risk of rupture into pericardium)",
      "Multiple small abscesses responding to antibiotics (< 3 cm)",
      "Failed medical therapy",
    ],
    correctIndex: 2,
    subject: "Surgery",
    roleLevel: "senior",
    marks: 3,
  },
  {
    id: "sr_mcq_8",
    type: "mcq",
    text: "Thyroid storm (Thyrotoxic crisis) mein treatment sequence kya hai?",
    options: [
      "Radioiodine first, then PTU",
      "PTU first (blocks new synthesis), then Lugol's iodine (after 1 hour), then beta-blocker, steroids, supportive care",
      "Surgery immediately",
      "Methimazole alone in high dose",
    ],
    correctIndex: 1,
    subject: "Endocrinology",
    roleLevel: "senior",
    marks: 3,
  },
  {
    id: "sr_mcq_9",
    type: "mcq",
    text: "Goodpasture syndrome mein antibody target kaunsa hai?",
    options: [
      "ANA (antinuclear)",
      "Anti-GBM (anti-glomerular basement membrane) antibody — type IV collagen alpha-3",
      "ANCA (c-ANCA)",
      "Anti-dsDNA",
    ],
    correctIndex: 1,
    subject: "Nephrology",
    roleLevel: "senior",
    marks: 3,
  },
  {
    id: "sr_mcq_10",
    type: "mcq",
    text: "Neurocysticercosis (brain cysts from Taenia solium) ka treatment kya hai?",
    options: [
      "Surgery only",
      "Albendazole/Praziquantel + steroids + anti-epileptics (depends on stage)",
      "Antibiotics only",
      "Observation only",
    ],
    correctIndex: 1,
    subject: "Neurology",
    roleLevel: "senior",
    marks: 3,
  },

  // ─── Senior Level Descriptive (5 questions) ───────────────────────
  {
    id: "sr_desc_1",
    type: "descriptive",
    text: "Acute Respiratory Distress Syndrome (ARDS) ki Berlin definition likhein. ARDS mein ventilator management strategy (lung protective ventilation, prone positioning, neuromuscular blockade) detail mein describe karein. Prognosis factors kya hain?",
    subject: "Medicine",
    roleLevel: "senior",
    marks: 15,
  },
  {
    id: "sr_desc_2",
    type: "descriptive",
    text: "Portal hypertension ke complications (variceal bleeding, ascites, SBP, hepatorenal syndrome, hepatic encephalopathy) list karein. Har ek ki pathophysiology aur management outline karein. TIPS procedure ke indications kya hain?",
    subject: "Medicine",
    roleLevel: "senior",
    marks: 15,
  },
  {
    id: "sr_desc_3",
    type: "descriptive",
    text: "Diabetic Nephropathy ki staging (Mogensen classification) describe karein. Treatment approach — glycemic control, RAAS blockade, SGLT2 inhibitors ki role — explain karein. Dialysis ke indications kya hain?",
    subject: "Nephrology",
    roleLevel: "senior",
    marks: 15,
  },
  {
    id: "sr_desc_4",
    type: "descriptive",
    text: "Acute Liver Failure (ALF) ki definition aur etiology likhein. King's College Criteria for liver transplantation kya hain? ALF management mein cerebral edema monitoring aur liver support systems ki role describe karein.",
    subject: "Medicine",
    roleLevel: "senior",
    marks: 15,
  },
  {
    id: "sr_desc_5",
    type: "descriptive",
    text: "India mein Nipah virus infection ke epidemiology, pathogenesis, clinical features, diagnosis aur management describe karein. WHO ke response guidelines aur contact tracing protocol outline karein. Future outbreak prevention strategies kya hain?",
    subject: "Infectious Disease",
    roleLevel: "senior",
    marks: 15,
  },

  // ─── Professor Level MCQ (5 questions) ──────────────────────────
  {
    id: "prof_mcq_1",
    type: "mcq",
    text: "SGLT2 inhibitors (empagliflozin, dapagliflozin) in heart failure mein evidence-based benefit kya hai?",
    options: [
      "Only blood glucose lowering",
      "Reduced hospitalization for heart failure and cardiovascular death (EMPEROR-Reduced, DAPA-HF trials)",
      "Increased GFR only",
      "Primarily blood pressure lowering",
    ],
    correctIndex: 1,
    subject: "Cardiology",
    roleLevel: "professor",
    marks: 4,
  },
  {
    id: "prof_mcq_2",
    type: "mcq",
    text: "Anti-phospholipid syndrome diagnosis ke liye 2 separate positive test hone chahiye kitne interval ke saath?",
    options: [
      "2 weeks apart",
      "4 weeks apart",
      "12 weeks apart",
      "6 months apart",
    ],
    correctIndex: 2,
    subject: "Medicine",
    roleLevel: "professor",
    marks: 4,
  },
  {
    id: "prof_mcq_3",
    type: "mcq",
    text: "Clostridium difficile infection (CDI) recurrence mein most effective treatment kaunsa hai (2022 IDSA guidelines)?",
    options: [
      "Metronidazole repeated",
      "Vancomycin tapered course",
      "Fidaxomicin",
      "Fecal Microbiota Transplantation (FMT) for multiple recurrences",
    ],
    correctIndex: 3,
    subject: "Infectious Disease",
    roleLevel: "professor",
    marks: 4,
  },
  {
    id: "prof_mcq_4",
    type: "mcq",
    text: "COVID-19 mein IL-6 receptor antagonist (tocilizumab) ka use kab indicated hai?",
    options: [
      "Mild COVID-19 (ambulatory)",
      "Severe/critical COVID-19 with rapid respiratory deterioration + elevated inflammatory markers + on steroids",
      "Prophylaxis only",
      "Asymptomatic positive test",
    ],
    correctIndex: 1,
    subject: "Infectious Disease",
    roleLevel: "professor",
    marks: 4,
  },
  {
    id: "prof_mcq_5",
    type: "mcq",
    text: "CAR-T cell therapy ke major immune complications mein 'cytokine release syndrome' manage karne ke liye kya use hota hai?",
    options: [
      "Broad-spectrum antibiotics",
      "Tocilizumab (anti-IL-6)",
      "High-dose IVIG",
      "Rituximab",
    ],
    correctIndex: 1,
    subject: "Oncology",
    roleLevel: "professor",
    marks: 4,
  },

  // ─── Professor Level Descriptive (7 questions) ───────────────────
  {
    id: "prof_desc_1",
    type: "descriptive",
    text: "India mein Antimicrobial Resistance (AMR) ki current situation describe karein. NDM-1 (New Delhi Metallo-beta-lactamase) ki discovery, mechanism, aur global significance explain karein. AMR combat ke liye national action plan (NAPA) ke key components kya hain?",
    subject: "Infectious Disease",
    roleLevel: "professor",
    marks: 20,
  },
  {
    id: "prof_desc_2",
    type: "descriptive",
    text: "Precision medicine ka concept explain karein. Oncology mein targeted therapy (TKIs, checkpoint inhibitors, ADCs) ke examples dein. Biomarker testing aur tumor mutational burden (TMB) ki role describe karein. India mein precision medicine ke challenges kya hain?",
    subject: "Oncology",
    roleLevel: "professor",
    marks: 20,
  },
  {
    id: "prof_desc_3",
    type: "descriptive",
    text: "CRISPR-Cas9 gene editing ka mechanism explain karein. Medical applications (sickle cell disease cure, cancer therapy, infectious disease) describe karein. Ethical considerations aur germline editing ke controversies discuss karein.",
    subject: "Medicine",
    roleLevel: "professor",
    marks: 20,
  },
  {
    id: "prof_desc_4",
    type: "descriptive",
    text: "India mein non-alcoholic fatty liver disease (NAFLD) / NASH epidemic describe karein. NASH ka natural history, diagnosis (FIB-4 score, liver biopsy, MR elastography), aur emerging therapies (resmetirom, semaglutide) review karein. NASH cirrhosis mein HCC surveillance ka role explain karein.",
    subject: "Medicine",
    roleLevel: "professor",
    marks: 20,
  },
  {
    id: "prof_desc_5",
    type: "descriptive",
    text: "Organ transplantation mein immunosuppression protocols describe karein. Calcineurin inhibitors, mTOR inhibitors, anti-metabolites ka mechanism aur side effects explain karein. Rejection types (hyperacute, acute, chronic) aur their management describe karein.",
    subject: "Surgery",
    roleLevel: "professor",
    marks: 20,
  },
  {
    id: "prof_desc_6",
    type: "descriptive",
    text: "India mein pandemic preparedness — COVID-19 ke lessons describe karein. One Health approach (human-animal-environment interface) explain karein. Zoonotic spillover events (Nipah, KFD, bird flu H5N1) ke risk factors aur India-specific surveillance systems describe karein.",
    subject: "Public Health",
    roleLevel: "professor",
    marks: 20,
  },
  {
    id: "prof_desc_7",
    type: "descriptive",
    text: "Clinical trials — Phase I se Phase IV tak describe karein. RCT design, blinding, randomization, power calculation explain karein. India mein DCGI regulations aur GCP guidelines outline karein. EBM (Evidence-Based Medicine) pyramid aur GRADE system kya hai?",
    subject: "Community Medicine",
    roleLevel: "professor",
    marks: 20,
  },

  // ─── HOD Level MCQ (3 questions) ──────────────────────────────────
  {
    id: "hod_mcq_1",
    type: "mcq",
    text: "NASH-related cirrhosis mein HCC screening protocol kya hai (AASLD guidelines)?",
    options: [
      "Annual AFP only",
      "Ultrasound every 6 months ± AFP",
      "CT scan every 3 months",
      "MRI annually",
    ],
    correctIndex: 1,
    subject: "Medicine",
    roleLevel: "hod",
    marks: 5,
  },
  {
    id: "hod_mcq_2",
    type: "mcq",
    text: "India mein medical education accreditation body kaunsi hai?",
    options: [
      "IMA (Indian Medical Association)",
      "NMC (National Medical Commission) — replaced MCI in 2020",
      "ICMR",
      "AIIMS Central Board",
    ],
    correctIndex: 1,
    subject: "Community Medicine",
    roleLevel: "hod",
    marks: 5,
  },
  {
    id: "hod_mcq_3",
    type: "mcq",
    text: "Competency-based medical education (CBME) curriculum India mein kis year se implement hua?",
    options: ["2010", "2015", "2019", "2023"],
    correctIndex: 2,
    subject: "Community Medicine",
    roleLevel: "hod",
    marks: 5,
  },

  // ─── HOD Level Descriptive (5 questions) ─────────────────────────
  {
    id: "hod_desc_1",
    type: "descriptive",
    text: "Hospital-acquired infection (HAI) prevention program design karein apne department ke liye. Surveillance metrics, antibiogram analysis, MRSA/VRE decolonization protocols, carbapenem-resistant organism (CRO) outbreak response, aur stewardship committee ka structure describe karein. Quality indicators aur benchmarking kaise karein?",
    subject: "Infectious Disease",
    roleLevel: "hod",
    marks: 25,
  },
  {
    id: "hod_desc_2",
    type: "descriptive",
    text: "India mein medical education reform ki zarurat kyo hai? CBME curriculum ke strengths aur limitations analyze karein. Simulation-based learning, OSCE assessment, aur entrustable professional activities (EPAs) ka role describe karein. HOD level pe faculty development program kaise design karein?",
    subject: "Community Medicine",
    roleLevel: "hod",
    marks: 25,
  },
  {
    id: "hod_desc_3",
    type: "descriptive",
    text: "Critical care department mein ICU quality metrics define karein (VAP rates, CLABSI, CAUTI, mortality indices). Performance improvement program kaise run karein? Team huddle, rapid response systems, aur simulation-based crisis training ka implementation describe karein. How would you achieve ICU accreditation?",
    subject: "Medicine",
    roleLevel: "hod",
    marks: 25,
  },
  {
    id: "hod_desc_4",
    type: "descriptive",
    text: "India mein Non-Communicable Disease (NCD) burden ka evidence-based analysis karein. NPCDCS program evaluate karein. Cardiovascular disease, diabetes, cancer, aur COPD ke integrated management ke liye district-level health system kaise strengthen karein? Social determinants of health ka role discuss karein.",
    subject: "Public Health",
    roleLevel: "hod",
    marks: 25,
  },
  {
    id: "hod_desc_5",
    type: "descriptive",
    text: "Research ethics committee (IEC/IRB) ke functions describe karein. Informed consent process, vulnerable population protection, aur clinical trial ethics outline karein. Research misconduct (plagiarism, data fabrication) ke liye institutional policies kaise design karein? ICMR national ethical guidelines ke key principles kya hain?",
    subject: "Community Medicine",
    roleLevel: "hod",
    marks: 25,
  },
];

// Get questions by role
export function getQuestionsForRole(role: string): ExamQuestion[] {
  const roleMap: Record<string, ExamQuestion["roleLevel"]> = {
    mbbs: "mbbs",
    intern: "mbbs",
    jr1: "junior",
    jr2: "junior",
    junior: "junior",
    sr1: "senior",
    sr2: "senior",
    senior: "senior",
    professor: "professor",
    hod: "hod",
  };

  const level = roleMap[role] || "mbbs";
  return EXAM_SEED_QUESTIONS.filter((q) => q.roleLevel === level);
}

// MCQ count per role
export const ROLE_MCQ_COUNT: Record<string, number> = {
  mbbs: 20,
  intern: 20,
  jr1: 15,
  jr2: 15,
  junior: 15,
  sr1: 10,
  sr2: 10,
  senior: 10,
  professor: 5,
  hod: 3,
};

// Descriptive count per role
export const ROLE_DESC_COUNT: Record<string, number> = {
  mbbs: 0,
  intern: 0,
  jr1: 3,
  jr2: 3,
  junior: 3,
  sr1: 5,
  sr2: 5,
  senior: 5,
  professor: 7,
  hod: 5,
};
