/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Symptom = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'severity' : IDL.Nat,
});
export const ClinicalSigns = IDL.Record({
  'bp' : IDL.Text,
  'hr' : IDL.Text,
  'rr' : IDL.Text,
  'spo2' : IDL.Text,
  'temp' : IDL.Text,
});
export const GoodEffect = IDL.Record({
  'description' : IDL.Text,
  'timeMinutes' : IDL.Nat,
});
export const SideEffect = IDL.Record({
  'description' : IDL.Text,
  'timeMinutes' : IDL.Nat,
});
export const Medicine = IDL.Record({
  'id' : IDL.Text,
  'goodEffects' : IDL.Vec(GoodEffect),
  'duration' : IDL.Text,
  'dosage' : IDL.Text,
  'name' : IDL.Text,
  'contraindications' : IDL.Vec(IDL.Text),
  'drugInteractions' : IDL.Vec(IDL.Text),
  'sideEffects' : IDL.Vec(SideEffect),
  'route' : IDL.Text,
});
export const Disease = IDL.Record({
  'id' : IDL.Text,
  'diagnosticCriteria' : IDL.Text,
  'name' : IDL.Text,
  'icd10Code' : IDL.Text,
  'subjectMapping' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'category' : IDL.Text,
  'symptoms' : IDL.Vec(Symptom),
  'clinicalSigns' : ClinicalSigns,
  'medicines' : IDL.Vec(Medicine),
  'associatedDiseases' : IDL.Vec(IDL.Text),
});
export const PatientCase = IDL.Record({
  'id' : IDL.Text,
  'patientAge' : IDL.Nat,
  'title' : IDL.Text,
  'diseaseId' : IDL.Text,
  'subject' : IDL.Text,
  'patientGender' : IDL.Text,
  'patientDisability' : IDL.Opt(IDL.Text),
  'difficulty' : IDL.Text,
  'correctDiagnosis' : IDL.Text,
  'history' : IDL.Text,
  'examinationFindings' : IDL.Text,
  'correctMedicines' : IDL.Vec(IDL.Text),
  'investigations' : IDL.Text,
  'chiefComplaint' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AdminAlert = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Time,
  'message' : IDL.Text,
  'severity' : IDL.Nat,
});
export const Effect = IDL.Record({
  'description' : IDL.Text,
  'timeMinutes' : IDL.Nat,
});
export const Diagnosis = IDL.Record({
  'diseaseId' : IDL.Text,
  'name' : IDL.Text,
  'icd10Code' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'symptoms' : IDL.Vec(Symptom),
});
export const Outcome = IDL.Record({
  'isCorrect' : IDL.Bool,
  'effectsTimeline' : IDL.Vec(Effect),
  'details' : IDL.Text,
  '_diagnosis' : IDL.Opt(Diagnosis),
  'responseTime' : Time,
});
export const VitalSigns = IDL.Record({
  'bp' : IDL.Text,
  'hr' : IDL.Nat,
  'rr' : IDL.Nat,
  'spo2' : IDL.Nat,
  'temp' : IDL.Nat,
});
export const PatientData = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'medicinesChosen' : IDL.Vec(IDL.Text),
  'hasDisability' : IDL.Bool,
  'history' : IDL.Text,
  'diagnosisAttempt' : IDL.Text,
  'gender' : IDL.Text,
  'symptoms' : IDL.Vec(IDL.Text),
  'outcome' : Outcome,
  'allergies' : IDL.Vec(IDL.Text),
  'vitals' : VitalSigns,
});
export const CustomPatientSession = IDL.Record({
  'id' : IDL.Text,
  'medicinesChosen' : IDL.Vec(IDL.Text),
  'studentId' : IDL.Text,
  'diagnosisAttempt' : IDL.Text,
  'patientData' : PatientData,
  'timestamp' : Time,
  'outcome' : Outcome,
});
export const AIResult = IDL.Record({
  'probability' : IDL.Nat,
  'diagnosis' : IDL.Vec(Diagnosis),
  'reasoning' : IDL.Text,
});
export const SecurityEvent = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'studentId' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'details' : IDL.Text,
  'eventType' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : IDL.Text,
  'isActive' : IDL.Bool,
  'mobile' : IDL.Text,
});
export const WrongMedicine = IDL.Record({
  'correctAlternative' : IDL.Text,
  'sideEffect' : IDL.Text,
  'medicineId' : IDL.Text,
  'reason' : IDL.Text,
});
export const WrongDiagnosis = IDL.Record({
  'explanation' : IDL.Text,
  'correctDiagnosis' : IDL.Text,
});
export const CaseAttempt = IDL.Record({
  'medicinesChosen' : IDL.Vec(IDL.Text),
  'studentId' : IDL.Text,
  'subject' : IDL.Text,
  'wrongMedicines' : IDL.Vec(WrongMedicine),
  'isCorrect' : IDL.Bool,
  'diagnosisChosen' : IDL.Text,
  'timestamp' : Time,
  'caseId' : IDL.Text,
  'outcome' : Outcome,
  'wrongDiagnosis' : IDL.Opt(WrongDiagnosis),
});
export const LeaderboardEntry = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'updatedAt' : Time,
  'points' : IDL.Nat,
});
export const SubjectStats = IDL.Vec(IDL.Text);
export const PerformanceStats = IDL.Record({
  'studentId' : IDL.Text,
  'caseHistory' : IDL.Vec(
    IDL.Record({
      'subjectName' : IDL.Text,
      'attempts' : IDL.Nat,
      'correct' : IDL.Nat,
      'accuracy' : IDL.Nat,
    })
  ),
  'recommendations' : IDL.Vec(IDL.Text),
  'weakSubjects' : IDL.Vec(IDL.Text),
  'subjectStats' : SubjectStats,
  'totalAttempts' : IDL.Nat,
  'correctCount' : IDL.Nat,
  'accuracy' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDisease' : IDL.Func([Disease], [], []),
  'addPatientCase' : IDL.Func([PatientCase], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAIEscalationAlert' : IDL.Func([AdminAlert], [], []),
  'createAdminAlert' : IDL.Func([AdminAlert], [], []),
  'createCustomPatientSession' : IDL.Func([CustomPatientSession], [], []),
  'deleteDisease' : IDL.Func([IDL.Text], [], []),
  'deletePatientCase' : IDL.Func([IDL.Text], [], []),
  'getAIDiagnosis' : IDL.Func([PatientData], [AIResult], []),
  'getAllAdminAlerts' : IDL.Func([], [IDL.Vec(AdminAlert)], ['query']),
  'getAllDiseases' : IDL.Func([], [IDL.Vec(Disease)], ['query']),
  'getAllPatientCases' : IDL.Func([], [IDL.Vec(PatientCase)], ['query']),
  'getAllSecurityEvents' : IDL.Func([], [IDL.Vec(SecurityEvent)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCaseAttemptsByStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CaseAttempt)],
      ['query'],
    ),
  'getCustomPatientSession' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CustomPatientSession)],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalStudents' : IDL.Nat,
          'activeToday' : IDL.Nat,
          'mostAttemptedCases' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          'commonMistakes' : IDL.Vec(IDL.Text),
        }),
      ],
      ['query'],
    ),
  'getDisease' : IDL.Func([IDL.Text], [IDL.Opt(Disease)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getMyCaseAttempts' : IDL.Func([], [IDL.Vec(CaseAttempt)], ['query']),
  'getMyCustomPatientSessions' : IDL.Func(
      [],
      [IDL.Vec(CustomPatientSession)],
      ['query'],
    ),
  'getMyPerformanceStats' : IDL.Func(
      [],
      [IDL.Opt(PerformanceStats)],
      ['query'],
    ),
  'getPatientCase' : IDL.Func([IDL.Text], [IDL.Opt(PatientCase)], ['query']),
  'getPerformanceStats' : IDL.Func([], [IDL.Vec(PerformanceStats)], ['query']),
  'getSecurityEventsByStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SecurityEvent)],
      ['query'],
    ),
  'getStudentPerformanceStats' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PerformanceStats)],
      ['query'],
    ),
  'getUnresolvedAdminAlerts' : IDL.Func([], [IDL.Vec(AdminAlert)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfileMobile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserProfileVerify' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'logSecurityEvent' : IDL.Func([SecurityEvent], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitCaseAttempt' : IDL.Func([CaseAttempt], [], []),
  'submitLeaderboardScore' : IDL.Func([IDL.Nat], [], []),
  'updateAdminAlertStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateDisease' : IDL.Func([Disease], [], []),
  'updatePatientCase' : IDL.Func([PatientCase], [], []),
  'updateSecurityEventStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateStudentStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Symptom = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'severity' : IDL.Nat,
  });
  const ClinicalSigns = IDL.Record({
    'bp' : IDL.Text,
    'hr' : IDL.Text,
    'rr' : IDL.Text,
    'spo2' : IDL.Text,
    'temp' : IDL.Text,
  });
  const GoodEffect = IDL.Record({
    'description' : IDL.Text,
    'timeMinutes' : IDL.Nat,
  });
  const SideEffect = IDL.Record({
    'description' : IDL.Text,
    'timeMinutes' : IDL.Nat,
  });
  const Medicine = IDL.Record({
    'id' : IDL.Text,
    'goodEffects' : IDL.Vec(GoodEffect),
    'duration' : IDL.Text,
    'dosage' : IDL.Text,
    'name' : IDL.Text,
    'contraindications' : IDL.Vec(IDL.Text),
    'drugInteractions' : IDL.Vec(IDL.Text),
    'sideEffects' : IDL.Vec(SideEffect),
    'route' : IDL.Text,
  });
  const Disease = IDL.Record({
    'id' : IDL.Text,
    'diagnosticCriteria' : IDL.Text,
    'name' : IDL.Text,
    'icd10Code' : IDL.Text,
    'subjectMapping' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'category' : IDL.Text,
    'symptoms' : IDL.Vec(Symptom),
    'clinicalSigns' : ClinicalSigns,
    'medicines' : IDL.Vec(Medicine),
    'associatedDiseases' : IDL.Vec(IDL.Text),
  });
  const PatientCase = IDL.Record({
    'id' : IDL.Text,
    'patientAge' : IDL.Nat,
    'title' : IDL.Text,
    'diseaseId' : IDL.Text,
    'subject' : IDL.Text,
    'patientGender' : IDL.Text,
    'patientDisability' : IDL.Opt(IDL.Text),
    'difficulty' : IDL.Text,
    'correctDiagnosis' : IDL.Text,
    'history' : IDL.Text,
    'examinationFindings' : IDL.Text,
    'correctMedicines' : IDL.Vec(IDL.Text),
    'investigations' : IDL.Text,
    'chiefComplaint' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AdminAlert = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Time,
    'message' : IDL.Text,
    'severity' : IDL.Nat,
  });
  const Effect = IDL.Record({
    'description' : IDL.Text,
    'timeMinutes' : IDL.Nat,
  });
  const Diagnosis = IDL.Record({
    'diseaseId' : IDL.Text,
    'name' : IDL.Text,
    'icd10Code' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'symptoms' : IDL.Vec(Symptom),
  });
  const Outcome = IDL.Record({
    'isCorrect' : IDL.Bool,
    'effectsTimeline' : IDL.Vec(Effect),
    'details' : IDL.Text,
    '_diagnosis' : IDL.Opt(Diagnosis),
    'responseTime' : Time,
  });
  const VitalSigns = IDL.Record({
    'bp' : IDL.Text,
    'hr' : IDL.Nat,
    'rr' : IDL.Nat,
    'spo2' : IDL.Nat,
    'temp' : IDL.Nat,
  });
  const PatientData = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'medicinesChosen' : IDL.Vec(IDL.Text),
    'hasDisability' : IDL.Bool,
    'history' : IDL.Text,
    'diagnosisAttempt' : IDL.Text,
    'gender' : IDL.Text,
    'symptoms' : IDL.Vec(IDL.Text),
    'outcome' : Outcome,
    'allergies' : IDL.Vec(IDL.Text),
    'vitals' : VitalSigns,
  });
  const CustomPatientSession = IDL.Record({
    'id' : IDL.Text,
    'medicinesChosen' : IDL.Vec(IDL.Text),
    'studentId' : IDL.Text,
    'diagnosisAttempt' : IDL.Text,
    'patientData' : PatientData,
    'timestamp' : Time,
    'outcome' : Outcome,
  });
  const AIResult = IDL.Record({
    'probability' : IDL.Nat,
    'diagnosis' : IDL.Vec(Diagnosis),
    'reasoning' : IDL.Text,
  });
  const SecurityEvent = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'studentId' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'details' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : IDL.Text,
    'isActive' : IDL.Bool,
    'mobile' : IDL.Text,
  });
  const WrongMedicine = IDL.Record({
    'correctAlternative' : IDL.Text,
    'sideEffect' : IDL.Text,
    'medicineId' : IDL.Text,
    'reason' : IDL.Text,
  });
  const WrongDiagnosis = IDL.Record({
    'explanation' : IDL.Text,
    'correctDiagnosis' : IDL.Text,
  });
  const CaseAttempt = IDL.Record({
    'medicinesChosen' : IDL.Vec(IDL.Text),
    'studentId' : IDL.Text,
    'subject' : IDL.Text,
    'wrongMedicines' : IDL.Vec(WrongMedicine),
    'isCorrect' : IDL.Bool,
    'diagnosisChosen' : IDL.Text,
    'timestamp' : Time,
    'caseId' : IDL.Text,
    'outcome' : Outcome,
    'wrongDiagnosis' : IDL.Opt(WrongDiagnosis),
  });
  const LeaderboardEntry = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'updatedAt' : Time,
    'points' : IDL.Nat,
  });
  const SubjectStats = IDL.Vec(IDL.Text);
  const PerformanceStats = IDL.Record({
    'studentId' : IDL.Text,
    'caseHistory' : IDL.Vec(
      IDL.Record({
        'subjectName' : IDL.Text,
        'attempts' : IDL.Nat,
        'correct' : IDL.Nat,
        'accuracy' : IDL.Nat,
      })
    ),
    'recommendations' : IDL.Vec(IDL.Text),
    'weakSubjects' : IDL.Vec(IDL.Text),
    'subjectStats' : SubjectStats,
    'totalAttempts' : IDL.Nat,
    'correctCount' : IDL.Nat,
    'accuracy' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDisease' : IDL.Func([Disease], [], []),
    'addPatientCase' : IDL.Func([PatientCase], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAIEscalationAlert' : IDL.Func([AdminAlert], [], []),
    'createAdminAlert' : IDL.Func([AdminAlert], [], []),
    'createCustomPatientSession' : IDL.Func([CustomPatientSession], [], []),
    'deleteDisease' : IDL.Func([IDL.Text], [], []),
    'deletePatientCase' : IDL.Func([IDL.Text], [], []),
    'getAIDiagnosis' : IDL.Func([PatientData], [AIResult], []),
    'getAllAdminAlerts' : IDL.Func([], [IDL.Vec(AdminAlert)], ['query']),
    'getAllDiseases' : IDL.Func([], [IDL.Vec(Disease)], ['query']),
    'getAllPatientCases' : IDL.Func([], [IDL.Vec(PatientCase)], ['query']),
    'getAllSecurityEvents' : IDL.Func([], [IDL.Vec(SecurityEvent)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCaseAttemptsByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CaseAttempt)],
        ['query'],
      ),
    'getCustomPatientSession' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CustomPatientSession)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalStudents' : IDL.Nat,
            'activeToday' : IDL.Nat,
            'mostAttemptedCases' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
            'commonMistakes' : IDL.Vec(IDL.Text),
          }),
        ],
        ['query'],
      ),
    'getDisease' : IDL.Func([IDL.Text], [IDL.Opt(Disease)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getMyCaseAttempts' : IDL.Func([], [IDL.Vec(CaseAttempt)], ['query']),
    'getMyCustomPatientSessions' : IDL.Func(
        [],
        [IDL.Vec(CustomPatientSession)],
        ['query'],
      ),
    'getMyPerformanceStats' : IDL.Func(
        [],
        [IDL.Opt(PerformanceStats)],
        ['query'],
      ),
    'getPatientCase' : IDL.Func([IDL.Text], [IDL.Opt(PatientCase)], ['query']),
    'getPerformanceStats' : IDL.Func(
        [],
        [IDL.Vec(PerformanceStats)],
        ['query'],
      ),
    'getSecurityEventsByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SecurityEvent)],
        ['query'],
      ),
    'getStudentPerformanceStats' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PerformanceStats)],
        ['query'],
      ),
    'getUnresolvedAdminAlerts' : IDL.Func([], [IDL.Vec(AdminAlert)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfileMobile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserProfileVerify' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'logSecurityEvent' : IDL.Func([SecurityEvent], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitCaseAttempt' : IDL.Func([CaseAttempt], [], []),
    'submitLeaderboardScore' : IDL.Func([IDL.Nat], [], []),
    'updateAdminAlertStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateDisease' : IDL.Func([Disease], [], []),
    'updatePatientCase' : IDL.Func([PatientCase], [], []),
    'updateSecurityEventStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateStudentStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };