/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIResult {
  'probability' : bigint,
  'diagnosis' : Array<Diagnosis>,
  'reasoning' : string,
}
export interface AdminAlert {
  'id' : string,
  'status' : string,
  'title' : string,
  'createdAt' : Time,
  'message' : string,
  'severity' : bigint,
}
export interface CaseAttempt {
  'medicinesChosen' : Array<string>,
  'studentId' : string,
  'subject' : string,
  'wrongMedicines' : Array<WrongMedicine>,
  'isCorrect' : boolean,
  'diagnosisChosen' : string,
  'timestamp' : Time,
  'caseId' : string,
  'outcome' : Outcome,
  'wrongDiagnosis' : [] | [WrongDiagnosis],
}
export interface ClinicalSigns {
  'bp' : string,
  'hr' : string,
  'rr' : string,
  'spo2' : string,
  'temp' : string,
}
export interface CustomPatientSession {
  'id' : string,
  'medicinesChosen' : Array<string>,
  'studentId' : string,
  'diagnosisAttempt' : string,
  'patientData' : PatientData,
  'timestamp' : Time,
  'outcome' : Outcome,
}
export interface Diagnosis {
  'diseaseId' : string,
  'name' : string,
  'icd10Code' : string,
  'description' : string,
  'category' : string,
  'symptoms' : Array<Symptom>,
}
export interface Disease {
  'id' : string,
  'diagnosticCriteria' : string,
  'name' : string,
  'icd10Code' : string,
  'subjectMapping' : Array<string>,
  'description' : string,
  'category' : string,
  'symptoms' : Array<Symptom>,
  'clinicalSigns' : ClinicalSigns,
  'medicines' : Array<Medicine>,
  'associatedDiseases' : Array<string>,
}
export interface Effect { 'description' : string, 'timeMinutes' : bigint }
export interface GoodEffect { 'description' : string, 'timeMinutes' : bigint }
export interface LeaderboardEntry {
  'id' : string,
  'name' : string,
  'role' : string,
  'updatedAt' : Time,
  'points' : bigint,
}
export interface Medicine {
  'id' : string,
  'goodEffects' : Array<GoodEffect>,
  'duration' : string,
  'dosage' : string,
  'name' : string,
  'contraindications' : Array<string>,
  'drugInteractions' : Array<string>,
  'sideEffects' : Array<SideEffect>,
  'route' : string,
}
export interface Outcome {
  'isCorrect' : boolean,
  'effectsTimeline' : Array<Effect>,
  'details' : string,
  '_diagnosis' : [] | [Diagnosis],
  'responseTime' : Time,
}
export interface PatientCase {
  'id' : string,
  'patientAge' : bigint,
  'title' : string,
  'diseaseId' : string,
  'subject' : string,
  'patientGender' : string,
  'patientDisability' : [] | [string],
  'difficulty' : string,
  'correctDiagnosis' : string,
  'history' : string,
  'examinationFindings' : string,
  'correctMedicines' : Array<string>,
  'investigations' : string,
  'chiefComplaint' : string,
}
export interface PatientData {
  'id' : string,
  'age' : bigint,
  'medicinesChosen' : Array<string>,
  'hasDisability' : boolean,
  'history' : string,
  'diagnosisAttempt' : string,
  'gender' : string,
  'symptoms' : Array<string>,
  'outcome' : Outcome,
  'allergies' : Array<string>,
  'vitals' : VitalSigns,
}
export interface PerformanceStats {
  'studentId' : string,
  'caseHistory' : Array<
    {
      'subjectName' : string,
      'attempts' : bigint,
      'correct' : bigint,
      'accuracy' : bigint,
    }
  >,
  'recommendations' : Array<string>,
  'weakSubjects' : Array<string>,
  'subjectStats' : SubjectStats,
  'totalAttempts' : bigint,
  'correctCount' : bigint,
  'accuracy' : bigint,
}
export interface SecurityEvent {
  'id' : string,
  'status' : string,
  'studentId' : [] | [string],
  'timestamp' : Time,
  'details' : string,
  'eventType' : string,
}
export interface SideEffect { 'description' : string, 'timeMinutes' : bigint }
export type SubjectStats = Array<string>;
export interface Symptom {
  'name' : string,
  'description' : string,
  'severity' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'role' : string,
  'isActive' : boolean,
  'mobile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VitalSigns {
  'bp' : string,
  'hr' : bigint,
  'rr' : bigint,
  'spo2' : bigint,
  'temp' : bigint,
}
export interface WrongDiagnosis {
  'explanation' : string,
  'correctDiagnosis' : string,
}
export interface WrongMedicine {
  'correctAlternative' : string,
  'sideEffect' : string,
  'medicineId' : string,
  'reason' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDisease' : ActorMethod<[Disease], undefined>,
  'addPatientCase' : ActorMethod<[PatientCase], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAIEscalationAlert' : ActorMethod<[AdminAlert], undefined>,
  'createAdminAlert' : ActorMethod<[AdminAlert], undefined>,
  'createCustomPatientSession' : ActorMethod<[CustomPatientSession], undefined>,
  'deleteDisease' : ActorMethod<[string], undefined>,
  'deletePatientCase' : ActorMethod<[string], undefined>,
  'getAIDiagnosis' : ActorMethod<[PatientData], AIResult>,
  'getAllAdminAlerts' : ActorMethod<[], Array<AdminAlert>>,
  'getAllDiseases' : ActorMethod<[], Array<Disease>>,
  'getAllPatientCases' : ActorMethod<[], Array<PatientCase>>,
  'getAllSecurityEvents' : ActorMethod<[], Array<SecurityEvent>>,
  'getAllStudents' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCaseAttemptsByStudent' : ActorMethod<[string], Array<CaseAttempt>>,
  'getCustomPatientSession' : ActorMethod<
    [string],
    [] | [CustomPatientSession]
  >,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'totalStudents' : bigint,
      'activeToday' : bigint,
      'mostAttemptedCases' : Array<[string, bigint]>,
      'commonMistakes' : Array<string>,
    }
  >,
  'getDisease' : ActorMethod<[string], [] | [Disease]>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getMyCaseAttempts' : ActorMethod<[], Array<CaseAttempt>>,
  'getMyCustomPatientSessions' : ActorMethod<[], Array<CustomPatientSession>>,
  'getMyPerformanceStats' : ActorMethod<[], [] | [PerformanceStats]>,
  'getPatientCase' : ActorMethod<[string], [] | [PatientCase]>,
  'getPerformanceStats' : ActorMethod<[], Array<PerformanceStats>>,
  'getSecurityEventsByStudent' : ActorMethod<[string], Array<SecurityEvent>>,
  'getStudentPerformanceStats' : ActorMethod<[string], [] | [PerformanceStats]>,
  'getUnresolvedAdminAlerts' : ActorMethod<[], Array<AdminAlert>>,
  'getUserProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'getUserProfileMobile' : ActorMethod<[string], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUserProfileVerify' : ActorMethod<[string], boolean>,
  'logSecurityEvent' : ActorMethod<[SecurityEvent], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitCaseAttempt' : ActorMethod<[CaseAttempt], undefined>,
  'submitLeaderboardScore' : ActorMethod<[bigint], undefined>,
  'updateAdminAlertStatus' : ActorMethod<[string, string], undefined>,
  'updateDisease' : ActorMethod<[Disease], undefined>,
  'updatePatientCase' : ActorMethod<[PatientCase], undefined>,
  'updateSecurityEventStatus' : ActorMethod<[string, string], undefined>,
  'updateStudentStatus' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];