/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AIResult {
    probability: bigint;
    diagnosis: Array<Diagnosis>;
    reasoning: string;
}
export type Time = bigint;
export interface SecurityEvent {
    id: string;
    status: string;
    studentId?: string;
    timestamp: Time;
    details: string;
    eventType: string;
}
export interface WrongDiagnosis {
    explanation: string;
    correctDiagnosis: string;
}
export interface SideEffect {
    description: string;
    timeMinutes: bigint;
}
export interface PatientCase {
    id: string;
    patientAge: bigint;
    title: string;
    diseaseId: string;
    subject: string;
    patientGender: string;
    patientDisability?: string;
    difficulty: string;
    correctDiagnosis: string;
    history: string;
    examinationFindings: string;
    correctMedicines: Array<string>;
    investigations: string;
    chiefComplaint: string;
}
export interface CaseAttempt {
    medicinesChosen: Array<string>;
    studentId: string;
    subject: string;
    wrongMedicines: Array<WrongMedicine>;
    isCorrect: boolean;
    diagnosisChosen: string;
    timestamp: Time;
    caseId: string;
    outcome: Outcome;
    wrongDiagnosis?: WrongDiagnosis;
}
export interface AdminAlert {
    id: string;
    status: string;
    title: string;
    createdAt: Time;
    message: string;
    severity: bigint;
}
export interface GoodEffect {
    description: string;
    timeMinutes: bigint;
}
export interface WrongMedicine {
    correctAlternative: string;
    sideEffect: string;
    medicineId: string;
    reason: string;
}
export type SubjectStats = Array<string>;
export interface PerformanceStats {
    studentId: string;
    caseHistory: Array<{
        subjectName: string;
        attempts: bigint;
        correct: bigint;
        accuracy: bigint;
    }>;
    recommendations: Array<string>;
    weakSubjects: Array<string>;
    subjectStats: SubjectStats;
    totalAttempts: bigint;
    correctCount: bigint;
    accuracy: bigint;
}
export interface PatientData {
    id: string;
    age: bigint;
    medicinesChosen: Array<string>;
    hasDisability: boolean;
    history: string;
    diagnosisAttempt: string;
    gender: string;
    symptoms: Array<string>;
    outcome: Outcome;
    allergies: Array<string>;
    vitals: VitalSigns;
}
export interface Outcome {
    isCorrect: boolean;
    effectsTimeline: Array<Effect>;
    details: string;
    _diagnosis?: Diagnosis;
    responseTime: Time;
}
export interface Effect {
    description: string;
    timeMinutes: bigint;
}
export interface Medicine {
    id: string;
    goodEffects: Array<GoodEffect>;
    duration: string;
    dosage: string;
    name: string;
    contraindications: Array<string>;
    drugInteractions: Array<string>;
    sideEffects: Array<SideEffect>;
    route: string;
}
export interface Disease {
    id: string;
    diagnosticCriteria: string;
    name: string;
    icd10Code: string;
    subjectMapping: Array<string>;
    description: string;
    category: string;
    symptoms: Array<Symptom>;
    clinicalSigns: ClinicalSigns;
    medicines: Array<Medicine>;
    associatedDiseases: Array<string>;
}
export interface ClinicalSigns {
    bp: string;
    hr: string;
    rr: string;
    spo2: string;
    temp: string;
}
export interface VitalSigns {
    bp: string;
    hr: bigint;
    rr: bigint;
    spo2: bigint;
    temp: bigint;
}
export interface CustomPatientSession {
    id: string;
    medicinesChosen: Array<string>;
    studentId: string;
    diagnosisAttempt: string;
    patientData: PatientData;
    timestamp: Time;
    outcome: Outcome;
}
export interface Symptom {
    name: string;
    description: string;
    severity: bigint;
}
export interface UserProfile {
    id: string;
    name: string;
    createdAt: Time;
    role: string;
    isActive: boolean;
    mobile: string;
}
export interface Diagnosis {
    diseaseId: string;
    name: string;
    icd10Code: string;
    description: string;
    category: string;
    symptoms: Array<Symptom>;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDisease(disease: Disease): Promise<void>;
    addPatientCase(patientCase: PatientCase): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAIEscalationAlert(alert: AdminAlert): Promise<void>;
    createAdminAlert(alert: AdminAlert): Promise<void>;
    createCustomPatientSession(session: CustomPatientSession): Promise<void>;
    deleteDisease(diseaseId: string): Promise<void>;
    deletePatientCase(caseId: string): Promise<void>;
    getAIDiagnosis(patientData: PatientData): Promise<AIResult>;
    getAllAdminAlerts(): Promise<Array<AdminAlert>>;
    getAllDiseases(): Promise<Array<Disease>>;
    getAllPatientCases(): Promise<Array<PatientCase>>;
    getAllSecurityEvents(): Promise<Array<SecurityEvent>>;
    getAllStudents(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCaseAttemptsByStudent(studentId: string): Promise<Array<CaseAttempt>>;
    getCustomPatientSession(sessionId: string): Promise<CustomPatientSession | null>;
    getDashboardStats(): Promise<{
        totalStudents: bigint;
        activeToday: bigint;
        mostAttemptedCases: Array<[string, bigint]>;
        commonMistakes: Array<string>;
    }>;
    getDisease(diseaseId: string): Promise<Disease | null>;
    getMyCaseAttempts(): Promise<Array<CaseAttempt>>;
    getMyCustomPatientSessions(): Promise<Array<CustomPatientSession>>;
    getMyPerformanceStats(): Promise<PerformanceStats | null>;
    getPatientCase(caseId: string): Promise<PatientCase | null>;
    getPerformanceStats(): Promise<Array<PerformanceStats>>;
    getSecurityEventsByStudent(studentId: string): Promise<Array<SecurityEvent>>;
    getStudentPerformanceStats(studentId: string): Promise<PerformanceStats | null>;
    getUnresolvedAdminAlerts(): Promise<Array<AdminAlert>>;
    getUserProfile(userId: string): Promise<UserProfile | null>;
    getUserProfileMobile(_mobile: string): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isUserProfileVerify(_id: string): Promise<boolean>;
    logSecurityEvent(event: SecurityEvent): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitCaseAttempt(attempt: CaseAttempt): Promise<void>;
    updateAdminAlertStatus(alertId: string, status: string): Promise<void>;
    updateDisease(disease: Disease): Promise<void>;
    updatePatientCase(patientCase: PatientCase): Promise<void>;
    updateSecurityEventStatus(eventId: string, status: string): Promise<void>;
    updateStudentStatus(studentId: string, isActive: boolean): Promise<void>;
}
import type { CaseAttempt as _CaseAttempt, CustomPatientSession as _CustomPatientSession, Diagnosis as _Diagnosis, Disease as _Disease, Effect as _Effect, Outcome as _Outcome, PatientCase as _PatientCase, PatientData as _PatientData, PerformanceStats as _PerformanceStats, SecurityEvent as _SecurityEvent, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, VitalSigns as _VitalSigns, WrongDiagnosis as _WrongDiagnosis, WrongMedicine as _WrongMedicine } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDisease(arg0: Disease): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDisease(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDisease(arg0);
            return result;
        }
    }
    async addPatientCase(arg0: PatientCase): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPatientCase(to_candid_PatientCase_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPatientCase(to_candid_PatientCase_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAIEscalationAlert(arg0: AdminAlert): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAIEscalationAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAIEscalationAlert(arg0);
            return result;
        }
    }
    async createAdminAlert(arg0: AdminAlert): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAdminAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAdminAlert(arg0);
            return result;
        }
    }
    async createCustomPatientSession(arg0: CustomPatientSession): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomPatientSession(to_candid_CustomPatientSession_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomPatientSession(to_candid_CustomPatientSession_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteDisease(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDisease(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDisease(arg0);
            return result;
        }
    }
    async deletePatientCase(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePatientCase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePatientCase(arg0);
            return result;
        }
    }
    async getAIDiagnosis(arg0: PatientData): Promise<AIResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getAIDiagnosis(to_candid_PatientData_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAIDiagnosis(to_candid_PatientData_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllAdminAlerts(): Promise<Array<AdminAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAdminAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAdminAlerts();
            return result;
        }
    }
    async getAllDiseases(): Promise<Array<Disease>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDiseases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDiseases();
            return result;
        }
    }
    async getAllPatientCases(): Promise<Array<PatientCase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatientCases();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatientCases();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSecurityEvents(): Promise<Array<SecurityEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSecurityEvents();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSecurityEvents();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStudents(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCaseAttemptsByStudent(arg0: string): Promise<Array<CaseAttempt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCaseAttemptsByStudent(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCaseAttemptsByStudent(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomPatientSession(arg0: string): Promise<CustomPatientSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomPatientSession(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomPatientSession(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<{
        totalStudents: bigint;
        activeToday: bigint;
        mostAttemptedCases: Array<[string, bigint]>;
        commonMistakes: Array<string>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getDisease(arg0: string): Promise<Disease | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDisease(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDisease(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyCaseAttempts(): Promise<Array<CaseAttempt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCaseAttempts();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCaseAttempts();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyCustomPatientSessions(): Promise<Array<CustomPatientSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCustomPatientSessions();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCustomPatientSessions();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPerformanceStats(): Promise<PerformanceStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPerformanceStats();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPerformanceStats();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatientCase(arg0: string): Promise<PatientCase | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientCase(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientCase(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPerformanceStats(): Promise<Array<PerformanceStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPerformanceStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPerformanceStats();
            return result;
        }
    }
    async getSecurityEventsByStudent(arg0: string): Promise<Array<SecurityEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSecurityEventsByStudent(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSecurityEventsByStudent(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentPerformanceStats(arg0: string): Promise<PerformanceStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentPerformanceStats(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentPerformanceStats(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnresolvedAdminAlerts(): Promise<Array<AdminAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnresolvedAdminAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnresolvedAdminAlerts();
            return result;
        }
    }
    async getUserProfile(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfileMobile(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfileMobile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfileMobile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isUserProfileVerify(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserProfileVerify(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserProfileVerify(arg0);
            return result;
        }
    }
    async logSecurityEvent(arg0: SecurityEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logSecurityEvent(to_candid_SecurityEvent_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logSecurityEvent(to_candid_SecurityEvent_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitCaseAttempt(arg0: CaseAttempt): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCaseAttempt(to_candid_CaseAttempt_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCaseAttempt(to_candid_CaseAttempt_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAdminAlertStatus(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminAlertStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminAlertStatus(arg0, arg1);
            return result;
        }
    }
    async updateDisease(arg0: Disease): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDisease(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDisease(arg0);
            return result;
        }
    }
    async updatePatientCase(arg0: PatientCase): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatientCase(to_candid_PatientCase_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatientCase(to_candid_PatientCase_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSecurityEventStatus(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSecurityEventStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSecurityEventStatus(arg0, arg1);
            return result;
        }
    }
    async updateStudentStatus(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudentStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudentStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_CaseAttempt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaseAttempt): CaseAttempt {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_CustomPatientSession_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomPatientSession): CustomPatientSession {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Outcome_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Outcome): Outcome {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_PatientCase_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PatientCase): PatientCase {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PatientData_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PatientData): PatientData {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_SecurityEvent_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SecurityEvent): SecurityEvent {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Diagnosis]): Diagnosis | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WrongDiagnosis]): WrongDiagnosis | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomPatientSession]): CustomPatientSession | null {
    return value.length === 0 ? null : from_candid_CustomPatientSession_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Disease]): Disease | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PerformanceStats]): PerformanceStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PatientCase]): PatientCase | null {
    return value.length === 0 ? null : from_candid_PatientCase_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    patientAge: bigint;
    title: string;
    diseaseId: string;
    subject: string;
    patientGender: string;
    patientDisability: [] | [string];
    difficulty: string;
    correctDiagnosis: string;
    history: string;
    examinationFindings: string;
    correctMedicines: Array<string>;
    investigations: string;
    chiefComplaint: string;
}): {
    id: string;
    patientAge: bigint;
    title: string;
    diseaseId: string;
    subject: string;
    patientGender: string;
    patientDisability?: string;
    difficulty: string;
    correctDiagnosis: string;
    history: string;
    examinationFindings: string;
    correctMedicines: Array<string>;
    investigations: string;
    chiefComplaint: string;
} {
    return {
        id: value.id,
        patientAge: value.patientAge,
        title: value.title,
        diseaseId: value.diseaseId,
        subject: value.subject,
        patientGender: value.patientGender,
        patientDisability: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.patientDisability)),
        difficulty: value.difficulty,
        correctDiagnosis: value.correctDiagnosis,
        history: value.history,
        examinationFindings: value.examinationFindings,
        correctMedicines: value.correctMedicines,
        investigations: value.investigations,
        chiefComplaint: value.chiefComplaint
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    studentId: [] | [string];
    timestamp: _Time;
    details: string;
    eventType: string;
}): {
    id: string;
    status: string;
    studentId?: string;
    timestamp: Time;
    details: string;
    eventType: string;
} {
    return {
        id: value.id,
        status: value.status,
        studentId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.studentId)),
        timestamp: value.timestamp,
        details: value.details,
        eventType: value.eventType
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    medicinesChosen: Array<string>;
    studentId: string;
    subject: string;
    wrongMedicines: Array<_WrongMedicine>;
    isCorrect: boolean;
    diagnosisChosen: string;
    timestamp: _Time;
    caseId: string;
    outcome: _Outcome;
    wrongDiagnosis: [] | [_WrongDiagnosis];
}): {
    medicinesChosen: Array<string>;
    studentId: string;
    subject: string;
    wrongMedicines: Array<WrongMedicine>;
    isCorrect: boolean;
    diagnosisChosen: string;
    timestamp: Time;
    caseId: string;
    outcome: Outcome;
    wrongDiagnosis?: WrongDiagnosis;
} {
    return {
        medicinesChosen: value.medicinesChosen,
        studentId: value.studentId,
        subject: value.subject,
        wrongMedicines: value.wrongMedicines,
        isCorrect: value.isCorrect,
        diagnosisChosen: value.diagnosisChosen,
        timestamp: value.timestamp,
        caseId: value.caseId,
        outcome: from_candid_Outcome_n24(_uploadFile, _downloadFile, value.outcome),
        wrongDiagnosis: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.wrongDiagnosis))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isCorrect: boolean;
    effectsTimeline: Array<_Effect>;
    details: string;
    _diagnosis: [] | [_Diagnosis];
    responseTime: _Time;
}): {
    isCorrect: boolean;
    effectsTimeline: Array<Effect>;
    details: string;
    _diagnosis?: Diagnosis;
    responseTime: Time;
} {
    return {
        isCorrect: value.isCorrect,
        effectsTimeline: value.effectsTimeline,
        details: value.details,
        _diagnosis: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value._diagnosis)),
        responseTime: value.responseTime
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    medicinesChosen: Array<string>;
    studentId: string;
    diagnosisAttempt: string;
    patientData: _PatientData;
    timestamp: _Time;
    outcome: _Outcome;
}): {
    id: string;
    medicinesChosen: Array<string>;
    studentId: string;
    diagnosisAttempt: string;
    patientData: PatientData;
    timestamp: Time;
    outcome: Outcome;
} {
    return {
        id: value.id,
        medicinesChosen: value.medicinesChosen,
        studentId: value.studentId,
        diagnosisAttempt: value.diagnosisAttempt,
        patientData: from_candid_PatientData_n31(_uploadFile, _downloadFile, value.patientData),
        timestamp: value.timestamp,
        outcome: from_candid_Outcome_n24(_uploadFile, _downloadFile, value.outcome)
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    age: bigint;
    medicinesChosen: Array<string>;
    hasDisability: boolean;
    history: string;
    diagnosisAttempt: string;
    gender: string;
    symptoms: Array<string>;
    outcome: _Outcome;
    allergies: Array<string>;
    vitals: _VitalSigns;
}): {
    id: string;
    age: bigint;
    medicinesChosen: Array<string>;
    hasDisability: boolean;
    history: string;
    diagnosisAttempt: string;
    gender: string;
    symptoms: Array<string>;
    outcome: Outcome;
    allergies: Array<string>;
    vitals: VitalSigns;
} {
    return {
        id: value.id,
        age: value.age,
        medicinesChosen: value.medicinesChosen,
        hasDisability: value.hasDisability,
        history: value.history,
        diagnosisAttempt: value.diagnosisAttempt,
        gender: value.gender,
        symptoms: value.symptoms,
        outcome: from_candid_Outcome_n24(_uploadFile, _downloadFile, value.outcome),
        allergies: value.allergies,
        vitals: value.vitals
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PatientCase>): Array<PatientCase> {
    return value.map((x)=>from_candid_PatientCase_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SecurityEvent>): Array<SecurityEvent> {
    return value.map((x)=>from_candid_SecurityEvent_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CaseAttempt>): Array<CaseAttempt> {
    return value.map((x)=>from_candid_CaseAttempt_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomPatientSession>): Array<CustomPatientSession> {
    return value.map((x)=>from_candid_CustomPatientSession_n29(_uploadFile, _downloadFile, x));
}
function to_candid_CaseAttempt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CaseAttempt): _CaseAttempt {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_CustomPatientSession_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomPatientSession): _CustomPatientSession {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Outcome_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Outcome): _Outcome {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_PatientCase_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PatientCase): _PatientCase {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PatientData_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PatientData): _PatientData {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_SecurityEvent_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SecurityEvent): _SecurityEvent {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isCorrect: boolean;
    effectsTimeline: Array<Effect>;
    details: string;
    _diagnosis?: Diagnosis;
    responseTime: Time;
}): {
    isCorrect: boolean;
    effectsTimeline: Array<_Effect>;
    details: string;
    _diagnosis: [] | [_Diagnosis];
    responseTime: _Time;
} {
    return {
        isCorrect: value.isCorrect,
        effectsTimeline: value.effectsTimeline,
        details: value.details,
        _diagnosis: value._diagnosis ? candid_some(value._diagnosis) : candid_none(),
        responseTime: value.responseTime
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    patientAge: bigint;
    title: string;
    diseaseId: string;
    subject: string;
    patientGender: string;
    patientDisability?: string;
    difficulty: string;
    correctDiagnosis: string;
    history: string;
    examinationFindings: string;
    correctMedicines: Array<string>;
    investigations: string;
    chiefComplaint: string;
}): {
    id: string;
    patientAge: bigint;
    title: string;
    diseaseId: string;
    subject: string;
    patientGender: string;
    patientDisability: [] | [string];
    difficulty: string;
    correctDiagnosis: string;
    history: string;
    examinationFindings: string;
    correctMedicines: Array<string>;
    investigations: string;
    chiefComplaint: string;
} {
    return {
        id: value.id,
        patientAge: value.patientAge,
        title: value.title,
        diseaseId: value.diseaseId,
        subject: value.subject,
        patientGender: value.patientGender,
        patientDisability: value.patientDisability ? candid_some(value.patientDisability) : candid_none(),
        difficulty: value.difficulty,
        correctDiagnosis: value.correctDiagnosis,
        history: value.history,
        examinationFindings: value.examinationFindings,
        correctMedicines: value.correctMedicines,
        investigations: value.investigations,
        chiefComplaint: value.chiefComplaint
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    studentId?: string;
    timestamp: Time;
    details: string;
    eventType: string;
}): {
    id: string;
    status: string;
    studentId: [] | [string];
    timestamp: _Time;
    details: string;
    eventType: string;
} {
    return {
        id: value.id,
        status: value.status,
        studentId: value.studentId ? candid_some(value.studentId) : candid_none(),
        timestamp: value.timestamp,
        details: value.details,
        eventType: value.eventType
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    medicinesChosen: Array<string>;
    studentId: string;
    subject: string;
    wrongMedicines: Array<WrongMedicine>;
    isCorrect: boolean;
    diagnosisChosen: string;
    timestamp: Time;
    caseId: string;
    outcome: Outcome;
    wrongDiagnosis?: WrongDiagnosis;
}): {
    medicinesChosen: Array<string>;
    studentId: string;
    subject: string;
    wrongMedicines: Array<_WrongMedicine>;
    isCorrect: boolean;
    diagnosisChosen: string;
    timestamp: _Time;
    caseId: string;
    outcome: _Outcome;
    wrongDiagnosis: [] | [_WrongDiagnosis];
} {
    return {
        medicinesChosen: value.medicinesChosen,
        studentId: value.studentId,
        subject: value.subject,
        wrongMedicines: value.wrongMedicines,
        isCorrect: value.isCorrect,
        diagnosisChosen: value.diagnosisChosen,
        timestamp: value.timestamp,
        caseId: value.caseId,
        outcome: to_candid_Outcome_n9(_uploadFile, _downloadFile, value.outcome),
        wrongDiagnosis: value.wrongDiagnosis ? candid_some(value.wrongDiagnosis) : candid_none()
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    medicinesChosen: Array<string>;
    studentId: string;
    diagnosisAttempt: string;
    patientData: PatientData;
    timestamp: Time;
    outcome: Outcome;
}): {
    id: string;
    medicinesChosen: Array<string>;
    studentId: string;
    diagnosisAttempt: string;
    patientData: _PatientData;
    timestamp: _Time;
    outcome: _Outcome;
} {
    return {
        id: value.id,
        medicinesChosen: value.medicinesChosen,
        studentId: value.studentId,
        diagnosisAttempt: value.diagnosisAttempt,
        patientData: to_candid_PatientData_n7(_uploadFile, _downloadFile, value.patientData),
        timestamp: value.timestamp,
        outcome: to_candid_Outcome_n9(_uploadFile, _downloadFile, value.outcome)
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    age: bigint;
    medicinesChosen: Array<string>;
    hasDisability: boolean;
    history: string;
    diagnosisAttempt: string;
    gender: string;
    symptoms: Array<string>;
    outcome: Outcome;
    allergies: Array<string>;
    vitals: VitalSigns;
}): {
    id: string;
    age: bigint;
    medicinesChosen: Array<string>;
    hasDisability: boolean;
    history: string;
    diagnosisAttempt: string;
    gender: string;
    symptoms: Array<string>;
    outcome: _Outcome;
    allergies: Array<string>;
    vitals: _VitalSigns;
} {
    return {
        id: value.id,
        age: value.age,
        medicinesChosen: value.medicinesChosen,
        hasDisability: value.hasDisability,
        history: value.history,
        diagnosisAttempt: value.diagnosisAttempt,
        gender: value.gender,
        symptoms: value.symptoms,
        outcome: to_candid_Outcome_n9(_uploadFile, _downloadFile, value.outcome),
        allergies: value.allergies,
        vitals: value.vitals
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
